general: &general
  adapter: mysql2
  username: root
  password: root@123
  host: localhost
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *general
  database: mes_dev

production:
  <<: *general
  database: mes_production

test:
  <<: *general
  database: mes_test
